name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows external webhook trigger by bitbucket pipeline
  # https://bitbucket.org/canuda/canudax_lean/src/master/bitbucket-pipelines.yml
  repository_dispatch:
    types:
      - webhook

concurrency:
  group: canudax
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: einsteintoolkit/carpetx-test:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: main
          path: scripts

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Log triggering commit
        run: echo  ${{ github.event.client_payload.trigger }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: /bin/bash $GITHUB_WORKSPACE/scripts/bin/build-and-test.sh

      # set exit code based on test status
      - name: Exit code
        if: ${{env.TESTS_FAILED == 'True'}}
        run: exit 1
